[package]
name = "hello_lib"
version = "0.1.3"
edition = "2021"
authors = ["Ganesh Chandrasekaran"]
description = "Demo crate for demonstration"
documentation = "https://docs.rs/cargo/latest/cargo/"
readme="README.md"
license = "MIT OR Apache-2.0"
keywords = ["demo", "students"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
